apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^register$', views.register, name = 'register'),
	url(r'^login$', views.login, name = 'login'),
	url(r'^logout$', views.logout, name = 'logout'),
]

apps/wish/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.wish, name = 'wish'),
	url(r'^create$', views.create, name = 'create'),
	url(r'^add$', views.add, name = 'add'),
	url(r'^/item/(?P<id>\d+)', views.item, name = 'item'),
	url(r'^/copy/(?P<id>\d+)/(?P<user>\w+)', views.copy, name = 'copy'),
	url(r'^/delete/(?P<id>\d+)', views.delete, name = 'delete'),
	url(r'^/remove/(?P<id>\d+)/(?P<add>\w+)', views.remove, name = 'remove'),
]

exam/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^wish', include('apps.wish.urls', namespace='wish'))
]

apps/login/models.py
from __future__ import unicode_literals

from django.db import models
# from ..secrets.models import Secret

import re, md5

PW_REGEX = re.compile(r'^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$')

class userManager(models.Manager):
	def Regis(self, person):
		response = {}
		errors = []
		if len(person['name'])<3 or len(person['username']) < 3:
			errors.append('Name and username needs to be at least 3 characters')
		if len(person['password']) < 8:
			errors.append('Password must be at least 8 characters')
		if User.objects.filter(username = person['username']):
			errors.append('Username is taken!')		
		if not (person['password']) == (person['conf_pw']):
			errors.append('Passwords must match!')
		if len(person['hired']) < 1:
			errors.append('Date cant be left blank')
		if errors:
			response['status'] = False
			response['errors'] = errors
		else:
			hashed_pw = md5.new(person['password']).hexdigest()
			print "hashed_pw at regis", hashed_pw
			response['status'] = True
			response['person'] = self.create(name=person['name'], username=person['username'], hired=person['hired'], password=hashed_pw)
		return response

	def Login(self, person): #Coming in as request.POST
		response = {}
		try:
			user = self.get(username=person['username_login'])
			print user
			login_hash = md5.new(person['pw_login']).hexdigest()
			print "login hash:", login_hash
			print "user password:", user.password
			print "user username:", user.username

			if user.password == login_hash:
				print "passwords match!"
				response['status'] = True
				response['user'] = user
				return response
			else:
				response ['status'] = False
				return response
		except:
			print "failed!!!"

class User(models.Model):
	name = models.CharField(max_length=100)
	username = models.CharField(max_length=100)
	password = models.CharField(max_length=500)
	hired = models.DateField()
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

	objects = userManager()

apps/wish/models.py
from __future__ import unicode_literals

from django.db import models
from ..login.models import User


class wishManager(models.Manager):
	def Valid(self, new_wish):
		response = {}
		errors = []
		if len(new_wish) < 1:
			errors.append('Wishes cannot be blank!')
		if len(new_wish) < 4:
			errors.append('Wishes should be more than 3 characters')
		if errors:
			response['status'] = False
			response['errors'] = errors
		else:
			response['status'] = True
		return response

	def AddWish(self, new_wish, person):
		self.create(item=new_wish, user=person)

	def CopyWish(self, new_wish, person, user):
		# print "new wish: ", new_wish
		# print "person", person
		# print "user", user
		self.create(item=new_wish, user=person, add=user)

	def DeleteWish(self, new_wish, person):
		# self.get(item=new_wish, user=person).delete()
		self.get(item=new_wish, user=person).delete()
	# def AddLike(self, user_id, secret_id):
	# 	this_user = User.objects.get(id=user_id)
	# 	this_secret = self.get(id=secret_id)
	# 	like = this_secret.like.add(this_user)
	# 	return True

	def RemoveWish(self, new_wish, person, add):
		# self.get(item=new_wish, user=person).delete()
		self.get(item=new_wish, user=person, add=add).delete()

class Wish(models.Model):
	item = models.TextField()
	user = models.ForeignKey(User, related_name = 'user_wish')
	add = models.TextField(default="no")
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

	objects = wishManager()

apps/login/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse

from django.contrib import messages
from .models import User

def index(request):
	if 'name' in request.session:
		return redirect('wish:wish')
	return render(request, 'login/index.html')

def register(request):
	person = {
		'name': request.POST['name'],
		'username': request.POST['username'],
		'password': request.POST['password'],
		'conf_pw': request.POST['conf_pw'],
		'hired': request.POST['hired'],
	}

	if request.method != "POST":
		messages.add_message(request, messages.ERROR, "Cant have an empty form")
		return redirect("/")

	response = User.objects.Regis(person)

	if response['status'] == False:
		for error in response['errors']:
			messages.add_message(request, messages.ERROR, error)
		return redirect("/")
	else:
		messages.add_message(request, messages.SUCCESS, "You have registered!" )
		request.session['name'] = person['name']
		request.session['id'] = response['person'].id
	return redirect('wish:wish')

def login(request):
	if request.method == "POST":
		response = User.objects.Login(request.POST)
		if response['status'] == True:
			print "name: ", response['user'].name
			print "id: ", response['user'].id
			request.session['name'] = response['user'].name
			request.session['id'] = response['user'].id
		return redirect('wish:wish')
	else:
		for error in response['errors']:
			messages.error(request, error)
	return redirect('/')

def logout(request):
	request.session.flush()
	return redirect('/')
 

apps/wish/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse

from django.contrib import messages
from .models import Wish
from ..login.models import User

def wish(request):
	context = {
		'wishes': Wish.objects.all(),
		# 'total_likes': Secret.objects.annotate(total_likes=Count('likes')),
	}
	return render(request, 'wish/wish.html', context)

def create(request):
	return render(request, 'wish/create.html')
	# return render(request, 'wish/create.html')

def add(request):
	if request.method == 'POST':
		new_wish = request.POST['wish']
		# print 'here is the wish: ', request.POST['wish']
		person = User.objects.get(id=request.session['id'])
		# person = int(request.session['id'])
		# print 'person id right now: ', request.session['id']
		response = Wish.objects.Valid(new_wish)
	if response['status']:
		Wish.objects.AddWish(new_wish, person)
	else:
		for error in response['errors']:
			messages.error(request, error)
		return redirect('wish:create')
	return redirect('wish:wish')

def item(request, id):
	context = {
		# 'something': id
		'item': Wish.objects.filter(id=id),
	}
	print context
	return render(request, 'wish/item.html', context)

def copy(request, id, user):
	new_wish = Wish.objects.get(id=id).item
	# print "Wish is: ", new_wish
	person = User.objects.get(id=request.session['id'])
	Wish.objects.CopyWish(new_wish, person, user)
	return redirect('wish:wish')

def delete(request, id):
	new_wish = Wish.objects.get(id=id).item
	# print "new wishes name in views: ", new_wish
	person = User.objects.get(id=request.session['id'])
	Wish.objects.DeleteWish(new_wish, person)
	return redirect('wish:wish')

def remove(request, id, add):
	new_wish = Wish.objects.get(id=id).item
	person = User.objects.get(id=request.session['id'])
	Wish.objects.RemoveWish(new_wish, person, add)
	return redirect('wish:wish')

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
<head>
  <title>My Wishlist!</title>
  {% load staticfiles %}
  <!-- The line above tells Django to be ready to listen for static files -->
  <link rel="stylesheet" href="{% static 'css/index.css' %}"media="screen" title="no title"  charset="utf-8">
</head>
<body>
  <center>
  <h1>Welcome!</h1>
    <form action="/register" class="register" method="post">
      {% csrf_token %}
      <fieldset>
        <legend>Register</legend>
        <ul>
          <li>Name: <input type="text" name="name"></li>
          <li>Username: <input type="text" name="username"></li>
          <p>*Password should be at least 8 characters</p>
          <li>Password: <input type="password" name="password"></li>
          <li>Confirm Password: <input type="password" name="conf_pw"></li>
          <li>Date Hired: <input type="date" name="hired"></li>
          <li><input type="submit" name="register" value="Register"></li>
        </ul>
      </fieldset>
    </form>

    <div class="messages">
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
          </li>
        {% endfor %}
      </ul>
    {% endif %}
    </div>

    <form action="/login" method="post">
      {% csrf_token %}
      <fieldset>
        <legend>Login</legend>
        <ul>
          <li>Username: <input type="text" name="username_login"></li>
          <li>Password: <input type="password" name="pw_login"></li>
          <li><input type="submit" name="login" value="Login"></li>
        </ul>
      </fieldset>
    </form>

  </center>
</body>
</html>

apps/wish/templates/wish/create.html
<!DOCTYPE html>
<html>
<head>
	<title>Wishes!</title>
	{% load staticfiles %}
	<!-- The line above tells Django to be ready to listen for static files -->
	<link rel="stylesheet" href="{% static 'css/index.css' %}"media="screen" title="no title"  charset="utf-8">
</head>
<body>
	<h1>Create a New Wish Item</h1>
	<form action="{% url 'wish:add' %}" method="post">
		{% csrf_token %}
		Item/Product: <input type="text" name="wish">
		<input type="submit" name="add" value="Add">
	</form>
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
					{{ message }}
				</li>
			{% endfor %}
		</ul>
	{% endif %}
	<a href="/wish">Home</a>
	<a href="{% url 'login:logout' %}">Logout</a>
	
	

	<!-- <form >
		
		<textarea class="wish_box" name="content" placeholder="Your text here..."></textarea>
		<input type="submit" name="post" value="Post">
	</form>
	{% for wish in wishes %}
		<p>{{ wish.user.name }} said:<br>{{ wish.content }} {{ wish.created_at }} 
		wishs:{{ wish.likes }}
		<a href="/wishs/like/{{ wish.id }}">Like</a></p> -->
		<!-- <p>wish id: {{ wish.id }}</p> -->
		<!-- {% if wish.user.id == request.session.id %}
			<p>You posted this <a href="/wishs/deletepost/{{ wish.id }}">Delete</a></p>
		{% endif %}
	{% endfor %} -->
	
</body>
</html>

apps/wish/templates/wish/item.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ item.item }}</title>
	{% load staticfiles %}
	<!-- The line above tells Django to be ready to listen for static files -->
	<link rel="stylesheet" href="{% static 'css/index.css' %}"media="screen" title="no title"  charset="utf-8">
</head>
<body>
	{% for y in item %}
	<h1>{{ y.item }}</h1>
	{% endfor %}
	<p>Users who added this product/item under their wish list:</p>
	<ul>
		{% for x in item %}
		<li>{{ x.user.name }}</li>
		{% endfor %}
	</ul>
	

	<a href="/wish">Home</a>
	<a href="{% url 'login:logout' %}">Logout</a>

</body>
</html>

apps/wish/templates/wish/wish.html
<!DOCTYPE html>
<html>
<head>
	<title>Wishes!</title>
	{% load staticfiles %}
	<!-- The line above tells Django to be ready to listen for static files -->
	<link rel="stylesheet" href="{% static 'css/index.css' %}"media="screen" title="no title"  charset="utf-8">
</head>
<body>
	<h1>Hello, {{ request.session.name }}!</h1>
	<h3>Your id is {{ request.session.id }}</h3>
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
					{{ message }}
				</li>
			{% endfor %}
		</ul>
	{% endif %}
	<a href="{% url 'login:logout' %}">Logout</a>
	
	<br>
	<br>
	Your Wishlist
	<table>
		<tr>
			<th>Item</th>
			<th>Added By</th>
			<th>Date Added</th>
			<th>Action</th>
		</tr>
		{% for wish in wishes %}
			{% if wish.user.id == request.session.id %}
				<tr>
					<td><a href="/wish/item/{{ wish.id }}">{{ wish.item }}</a></td>

					{% if wish.add != "no" %}
					<td>{{ wish.add }}</td>
					{% else %}
					<td>{{ wish.user.name }}</td>
					{% endif %}

					<td>{{ wish.created_at }}</td>
			{% if wish.user.id == request.session.id and wish.add == "no" %}
					<td><a href="/wish/delete/{{ wish.id }}">Delete</a></td>
			{% else %}
					<td><a href="/wish/remove/{{ wish.id }}/{{ wish.add }}">Remove from my Wishlist</a></td>
			{% endif %}
			{% endif %}
				</tr>
		{% endfor %}
	</table>
	<br>
	<br>
	<br>
	Other Users' Wishlists
	<table>
		<tr>
			<th>Item</th>
			<th>Added By</th>
			<th>Date Added</th>
			<th>Action</th>
		</tr>
		{% for wish in wishes %}
				{% if wish.user.id != request.session.id %}
					<tr>
					<td><a href="/wish/item/{{ wish.id }}">{{ wish.item }}</a></td></td>
					<td>{{ wish.user.name }}</td>
					<td>{{ wish.created_at }}</td>
						{% if wish.user.id != request.session.id %}
							<td><a href="/wish/copy/{{ wish.id }}/{{ wish.user.name }}">Add to my Wishlist</a></td>
						{% else %}
						<td></td>
						{% endif %}
				{% endif %}
					</tr>
		{% endfor %}
	</table>
	<br>
	<br>
	<a href="{% url 'wish:create' %}">Add Item</a>
	
</body>
</html>